# Usign the Clean Blog theme

title: The DHAI Seminar
author: dhai-seminar
email: gabriel.peyre@ens.fr
description: When Digital Humanities Meet Artificial Intelligence
baseurl: ""
url: "https://dhai-seminar.github.io/"
github_username:  dhai-seminar

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
exclude: ["node_modules"]

name: The DHAI Seminar
gems:
  - jekyll-feed
  - jekyll-paginate
